# -*- coding: utf-8 -*-
"""EARTHQUAKE PREDICTOR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NGFCT0iGq7L_SleWMe7Y6CqdKnDYBxwv
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv("earthquake_1995-2023.csv")

# Magnitude distribution
plt.figure(figsize=(8,5))
plt.hist(df['magnitude'], bins=10)
plt.title("Earthquake Magnitude Distribution")
plt.xlabel("Magnitude")
plt.ylabel("Number of Earthquakes")
plt.show()